// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaq1dQvdqVcqAyyBn6pFrFOpusakpuSrw',
    appId: '1:513454201067:web:c5f8e5eb85cb2386fd06ae',
    messagingSenderId: '513454201067',
    projectId: 'fluted-arch-341414',
    authDomain: 'fluted-arch-341414.firebaseapp.com',
    databaseURL: 'https://fluted-arch-341414-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fluted-arch-341414.appspot.com',
    measurementId: 'G-21PML7RRG8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNsUI9v7DUcJzlXrQ5YNJBmRs7WYsMmx0',
    appId: '1:513454201067:android:42317aa1cd81b70dfd06ae',
    messagingSenderId: '513454201067',
    projectId: 'fluted-arch-341414',
    databaseURL: 'https://fluted-arch-341414-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fluted-arch-341414.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHsm1WHRrMKYwvKjtME6hzctxxIzODL18',
    appId: '1:513454201067:ios:ba0aefa2e3b1b021fd06ae',
    messagingSenderId: '513454201067',
    projectId: 'fluted-arch-341414',
    databaseURL: 'https://fluted-arch-341414-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fluted-arch-341414.appspot.com',
    iosClientId: '513454201067-tk45r2270m3pishe7aqnpfgdlboiv1g5.apps.googleusercontent.com',
    iosBundleId: 'com.example.vitalsenseapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHsm1WHRrMKYwvKjtME6hzctxxIzODL18',
    appId: '1:513454201067:ios:ba0aefa2e3b1b021fd06ae',
    messagingSenderId: '513454201067',
    projectId: 'fluted-arch-341414',
    databaseURL: 'https://fluted-arch-341414-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'fluted-arch-341414.appspot.com',
    iosClientId: '513454201067-tk45r2270m3pishe7aqnpfgdlboiv1g5.apps.googleusercontent.com',
    iosBundleId: 'com.example.vitalsenseapp',
  );
}
